import { Person, PersonI } from "../../archive/person";
import { createNode, deleteNode, getNode } from "../utils/crud";

export async function getPerson(id: string): Promise<Person | undefined> {
    const matchedNode: object | undefined = getNode('Person', 'id: $id', { id });
    
    if(matchedNode){
        return matchedNode as Person;
    }

    return undefined;
}

//person id will be overridden by id generated by DB 
export async function createPerson(person: Person): Promise<Person> {
    const createdPerson: object | undefined = await createNode('Person', prepPersonProps(person), person);
    
    return new Person(createdPerson as PersonI);
}

export async function deletePerson(id: string): Promise<Person | undefined> {
    const deletedPerson: object | undefined = await deleteNode('Person', 'id: $id', { id });

    return deletedPerson as Person;
}

function prepPersonProps(person: Person): string[] {
    const props: string[] = [`id:apoc.create.uuid()`];

    if(person.firstName) props.push('firstName: $firstName');
    if(person.secondName) props.push('secondName: $secondName');
    if(person.lastName) props.push('lastName: $lastName');
    if(person.birthDate) props.push('birthDate: $birthDate');
    if(person.deathDate) props.push('deathDate: $deathDate');

    return props;
}